### ISSUE TITLE
Autonomy and Subsystem Communication

### ISSUE THREAD

**Issue by jmcmah10** [BinghamtonRover/BurtOS-2#71] opened 2022-03-31 21:52 UTC
General:
- Autonomy network library (create a new instance of the object, specifically for autonomy)
- Autonomy drive mode (need to add)
	- Ignore the autonomy network library when in non-autonomy drive mode
	- Receive both autonomy and base station messages in autonomy

Subsystem:
- Callback handler for autonomy message

GanttStart: 2022-04-04
GanttDue: 2022-04-11

**Comment by Levi-Lesches** [comment] 2022-09-30 06:07
Closing as a duplicate of https://github.com/BinghamtonRover/Logistics/issues/13

**Closed by Levi-Lesches** 2022-09-30 06:07 UTC
Labels: onboard subsystem, autonomy, transfer
