### ISSUE TITLE
Implement the "Follow the Gap" autonomy algorithm

### ISSUE THREAD

**Issue by superdan-t** [BinghamtonRover/BurtOS-2#73] opened 2022-04-01 06:09 UTC
Source files can be placed in `src/autonomy` for now. Since it is Python, they do not need to be added to the build system. If the code has any dependencies, you can create a README.md in the folder listing them.

## Timeline
These dates are tentative and we can change them as we know more. By mid-April, we should be ready to test this implementation with live data from the RealSense. After this, we'll want to start thinking about full integration with the rover drive system.

GanttStart: 2022-03-24
GanttDue: 2022-04-28

**Comment by Levi-Lesches** [comment] 2022-09-30 06:28
Closing as duplicate of https://github.com/BinghamtonRover/Autonomy/issues/4

**Closed by Levi-Lesches** 2022-09-30 06:28 UTC
Labels: autonomy, transfer
